### ISSUE TITLE
Lizard scanner - Complexity / File measure exception for each file

### ISSUE THREAD

**Issue by stonedauwg** [Backelite/sonar-objective-c#21]
When the scanner is reading the lizard report, for each source file, most measures save fine, but the Complexity / File measure always throws the exception below. This occurs for each source file I have but does **not** cause the sonar runner job to fail. Is this a version incompatability or deprecation issue? I am using SonarQube 6.2 and the 0.6.0 version of the sonar-objective-c plugin
```
15:44:34.296 DEBUG - Save measure Complexity in Functions for file /Users/mobile/iPadClientApp/Classes/SignatureViewController.m
15:44:34.296 DEBUG - Save measure Function Distribution / Complexity for file /Users/mobile/iPadClientApp/Classes/SignatureViewController.m
15:44:34.296 DEBUG - Save measure Complexity for file /Users/mobile/iPadClientApp/Classes/ItemDetailController.m
15:44:34.296 DEBUG - Save measure Functions for file /Users/mobile/iPadClientApp/Classes/ItemDetailController.m
15:44:34.296 DEBUG - Save measure Complexity / File for file /Users/mobile/iPadClientApp/Classes/ItemDetailController.m
15:44:34.296 ERROR -  Exception -> iPadClientApp/Classes/ItemDetailController.m -> Complexity / File
java.lang.UnsupportedOperationException: Metric 'file_complexity' should not be computed by a Sensor
	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:240)
	at org.sonar.scanner.index.DefaultIndex.addMeasure(DefaultIndex.java:231)
	at org.sonar.scanner.deprecated.DeprecatedSensorContext.saveMeasure(DeprecatedSensorContext.java:131)
	at org.sonar.plugins.objectivec.complexity.LizardMeasurePersistor.saveMeasures(LizardMeasurePersistor.java:80)
	at org.sonar.plugins.objectivec.complexity.LizardSensor.analyse(LizardSensor.java:80)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:76)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
```

**Comment by fjtrujy** [comment]
Hello,
I'm suffering exactly the same error. I am using SonarQube 6.3 and the 0.6.0 version of the sonar-objective-c plugin

**Comment by ElesG** [comment]
Meet the same error with SonarQube 6.3.1 , Sonar Scanner 3.0.3 and the 0.6.1 version of the sonar-objective-c plugin. But have no idea.

**Comment by gtatgh** [comment]
Same error with SonarQube 6.5, Sonar Scanner 3.0.3.778, plugin version 0.6.1.

**Comment by pbernery** [comment]
I guess this is the same issue as https://github.com/Backelite/sonar-swift/issues/90.
The plugin seems to not be ready for SonarQube 6.x yet. We are investigating the issue.

**Comment by zippy1978** [comment]
Hi @stonedauwg,

The issue should be fixed in the release 0.6.2.

Regards,
Gilles

**Comment by croustibapt** [comment]
@zippy1978 I'm still experiencing this issue with the 0.6.2 release version. I use the 6.7 version of SonarQube.

```
ERROR:  Exception -> ./MyApp/main.m -> Complexity / File
java.lang.UnsupportedOperationException: Metric 'file_complexity' should not be computed by a Sensor
```
